[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
    "langchain-google-genai>=4.4.0",
    "langfuse>=4.15.4",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-postgres>=3.1.2",
    "pgvector>=0.5.0",
    "psycopg-pool>=3.3.2",
    "psycopg[binary,pool]>=3.3.6",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "resend>=2.47.0",
    "uvicorn>=0.53.0",
]
